name: erp-ta
on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    defaults:
      run:
        working-directory: ./
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: build and release to DockerHub
      env:
        REPO: simson613
        LAYER_NAME: erp-ta
      run: |
        docker build -t $LAYER_NAME  .
        docker tag $LAYER_NAME:latest $REPO/$LAYER_NAME:latest
        docker push $REPO/$LAYER_NAME:latest
  
